name = "ChargeTransport"
uuid = "25c3eafe-d88c-11e9-3031-f396758f002a"
version = "1.5.0"
authors = ["Dilara Abdel <dilara.abdel@wias-berlin.de>, Patricio Farrell <patricio.farrell@wias-berlin.de>", "Patrick Jaap <patrick.jaap@wias-berlin.de>"]

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LessUnitful = "f29f6376-6e90-4d80-80c9-fb8ec61203d5"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[sources]
GridVisualize = {path = "C:\\Users\\marie\\.julia\\dev\\GridVisualize"}

[compat]
Aqua = "0.8.14"
Compat = "4.18.0"
DocStringExtensions = "0.9"
ExtendableGrids = "1"
ForwardDiff = "1"
GridVisualize = "1.17"
Interpolations = "0.16"
LaTeXStrings = "1.4.0"
LessUnitful = "1.2.1"
Printf = "1.10"
Roots = "2.0"
SimplexGridFactory = "2.6.0"
Test = "1.10"
Triangulate = "3.0"
VoronoiFVM = "2.13, 3.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[targets]
test = ["Aqua", "SimplexGridFactory", "Test", "Triangulate"]
